server:
  port: 8762

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

  profiles:
    active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      management.context-path: /actuator
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

management:
  security:
    enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always