version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.8.2-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  arangodb:
    environment:
      ARANGO_ROOT_PASSWORD: $ARANGO_ROOT_PASSWORD
      ARANGO_USER_NAME: ${ARANGO_USER_NAME}
      ARANGO_USER_PASSWORD: $ARANGO_USER_PASSWORD
    build: arangodb
    image: piggymetrics-arangodb:3.6
    ports:
      - 8529:8529
    restart: always
    volumes:
      - /private/opt/arangodb:/var/lib/arangodb3
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: registry
    image: piggymetrics-registry:1.0.0
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: config
    image: piggymetrics-config:1.0.0
    restart: always
    ports:
      - 8762:8762
    depends_on:
      - registry
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: gateway
    image: piggymetrics-gateway:1.0.0
    restart: always
    depends_on:
      - config
    ports:
      - 80:8763
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      ARANGO_USER_NAME: ${ARANGO_USER_NAME}
      ARANGO_USER_PASSWORD: $ARANGO_USER_PASSWORD
    build: auth-service
    image: piggymetrics-auth-service:1.0.0
    restart: always
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      ARANGO_USER_NAME: ${ARANGO_USER_NAME}
      ARANGO_USER_PASSWORD: $ARANGO_USER_PASSWORD
    build: account-service
    image: piggymetrics-account-service:1.0.0
    restart: always
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      STATISTICS_SERVICE_PASSWORD: $STATISTICS_SERVICE_PASSWORD
      ARANGO_USER_NAME: ${ARANGO_USER_NAME}
      ARANGO_USER_PASSWORD: $ARANGO_USER_PASSWORD
    build: statistics-service
    image: piggymetrics-statistics-service:1.0.0
    restart: always
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      NOTIFICATION_SERVICE_PASSWORD: $NOTIFICATION_SERVICE_PASSWORD
      ARANGO_USER_NAME: ${ARANGO_USER_NAME}
      ARANGO_USER_PASSWORD: $ARANGO_USER_PASSWORD
    build: notification-service
    image: piggymetrics-notification-service:1.0.0
    restart: always
    depends_on:
      - config
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  admin-server:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: admin-server
    image: piggymetrics-admin-server:1.0.0
    restart: always
    depends_on:
      - config
    ports:
      - 9200:9200
    logging:
      options:
        max-size: "10m"
        max-file: "10"
