server:
  port: 9101
  servlet:
    context-path: /accounts

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:9100/uaa/oauth/token
      scope: server

#spring:
#  data:
#    mongodb:
#      host: mongodb
#      username: user
#      password: ${MONGODB_PASSWORD}
#      database: piggymetrics
#      port: 27017

spring:
  data:
    arangodb:
      hosts: localhost:8529
      user: user
      password: ${ARANGO_USER_PASSWORD}
      database: piggymetrics

feign:
  hystrix:
    enabled: true