server:
  port: 9101
  servlet:
    context-path: /accounts

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:9100/uaa/oauth/token
      scope: server

spring:
  data:
    mongodb:
      host: mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

feign:
  hystrix:
    enabled: true