server:
  port: 9101
  servlet:
    context-path: /accounts

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:9100/uaa/oauth/token
      scope: server

spring:
  data:
    arangodb:
      hosts: localhost:8529
      user: ${ARANGO_USER_NAME}
      password: ${ARANGO_USER_PASSWORD}
      database: piggymetrics

feign:
  hystrix:
    enabled: true