spring:
  boot:
    admin:
      discovery:
        enabled: true
        service-id: config-server

  rabbitmq:
    host: rabbitmq

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:9100/uaa/users/current
      filter-order: 3

management:
  security:
    enabled: false
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always