server:
  port: 9100
  servlet:
    context-path: /uaa

spring:
  data:
    arangodb:
      hosts: localhost:8529
      user: user
      password: ${ARANGO_USER_PASSWORD}
      database: piggymetrics
