server:
  port: 9103
  servlet:
    context-path: /statistics

security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:9100/uaa/oauth/token
      scope: server

spring:
  data:
    arangodb:
      hosts: localhost:8529
      user: ${ARANGO_USER_NAME}
      password: ${ARANGO_USER_PASSWORD}
      database: piggymetrics

rates:
  url: https://api.exchangeratesapi.io