server:
  port: 9103
  servlet:
    context-path: /statistics

security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:9100/uaa/oauth/token
      scope: server

spring:
  data:
    mongodb:
      host: mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

rates:
  url: https://api.exchangeratesapi.io